### ISSUE TITLE
Exception on POST request with no body 

### ISSUE THREAD

**Issue by MagdalenaHylinskaSKK** [DanielMrowca/HoneyComb#6]
In HoneyComb.WebApi/ModelBinding/DefaultModelBinderProvider.cs

An exception appears when POST request with no body is submitted.

**Comment by DanielMrowca** [comment]
Bug fixed in https://github.com/DanielMrowca/HoneyComb/commit/c05fd1e9bddf51fbb095bad0fda112808b273c16
